"use client";

import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "zh" | "en";

const translations = {
  zh: {
    // Auth
    login: "登录",
    register: "注册",
    logout: "退出",
    username: "用户名",
    password: "密码",
    confirmPassword: "确认密码",
    enterUsername: "输入用户名",
    enterPassword: "输入密码",
    loggingIn: "登录中...",
    registering: "注册中...",
    noAccount: "没有账号？",
    registerNow: "立即注册",
    hasAccount: "已有账号？",
    loginNow: "立即登录",
    // Home
    forumTitle: "AI 伦理论坛",
    forumSubtitle: "一个探讨 AI 伦理、分享创意与工具的开放社区",
    schoolName: "广东碧桂园学校",
    switchAccount: "切换账号",
    recentLogins: "最近登录",
    home: "首页",
    podcast: "播客专区",
    news: "新闻专区",
    tools: "AI工具推荐",
    forum: "发帖专区",
    creative: "创意专区",
    profile: "个人中心",
    settings: "设置",
    latestPosts: "最新帖子",
    noPostsYet: "暂无帖子，来发第一篇吧！",
    startDiscussion: "发起讨论",
    browseForum: "浏览论坛",
    lastUpdated: "更新于",
    autoRefresh: "自动刷新",
    refresh: "刷新",
    motto: "校训",
    // Forum list
    forumDiscussion: "论坛讨论",
    searchPlaceholder: "搜索讨论...",
    newPost: "+ 发起讨论",
    all: "全部",
    catAiSafety: "AI安全",
    catPrivacy: "隐私保护",
    catEthics: "伦理责任",
    catAcademic: "学术讨论",
    catSocial: "社会影响",
    catCreative: "创意想法",
    loading: "加载中...",
    noPosts: "暂无讨论",
    repliesCount: "条回复",
    // Post detail
    backToForum: "← 返回论坛",
    guestCannotLike: "🔒 游客模式，登录后可以点赞",
    liked: "已点赞",
    like: "点赞",
    replyCount: "条回复",
    replyPlaceholder: "发表你的看法...",
    postReply: "发布回复",
    noReplies: "暂无回复，快来第一个评论吧！",
    guestCannotReply: "游客模式不可回复",
    loginToParticipate: "后可参与讨论",
    loginLink: "登录",
    registerLink: "注册",
    postNotFound: "帖子不存在",
    replyFailed: "❌ 回复失败",
    // Bilingual toggle
    viewInChinese: "查看中文",
    viewInEnglish: "查看英文",
    translationNotAvailable: "暂无英文翻译",
    // New post
    newDiscussion: "发起新讨论",
    postTitle: "标题",
    titlePlaceholder: "输入讨论标题",
    titleEnLabel: "英文标题（选填）",
    titleEnPlaceholder: "Enter title in English (optional)",
    selectCategory: "选择分类",
    contentLabel: "内容",
    contentPlaceholder: "分享你的想法...",
    contentEnLabel: "英文内容（选填）",
    contentEnPlaceholder: "Share your thoughts in English (optional)",
    publish: "发布",
    publishing: "发布中...",
    fillRequired: "请填写所有必填字段",
    postSuccess: "✅ 发布成功！",
    publishFailed: "发布失败",
    guestCannotPost: "游客模式无法发帖",
    guestPostDesc: "发起讨论需要登录注册账号",
    // Profile
    myPosts: "我的帖子",
    myBookmarks: "我的收藏",
    myLikes: "我的点赞",
    myFollows: "我的关注",
    guestTitle: "游客",
    guestDesc: "游客账号 · 仅供浏览，无个人主页",
    loginAccount: "登录账号",
    registerAccount: "注册账号",
    guestRegisterHint: "注册后即可发帖、回复、点赞，查看个人数据",
    editProfile: "编辑资料",
    saveProfile: "保存",
    cancelEdit: "取消",
    changeAvatar: "更换头像",
    bioLabel: "个人简介",
    noPostsTab: "还没有发布过帖子",
    noBookmarks: "还没有收藏内容",
    noLikes: "还没有点赞过内容",
    noFollows: "还没有关注任何人",
    follow: "关注",
    unfollow: "取消关注",
    followingState: "已关注",
    followingBadge: "关注中",
    followedAt: "关注时间",
    followingSectionLabel: "来自关注的动态",
    guestCannotFollow: "🔒 游客模式，登录后可以关注",
    usernameEmpty: "用户名不能为空",
    usernameLimit: "用户名最多 10 个汉字或20 个字母",
    avatarSizeLimit: "图片大小不能超过 2 MB，请重新选择。",
    likedPost: "点赞的帖子",
    likedAt: "点赞时间",
    // Settings
    appearance: "外观",
    themeLabel: "主题",
    lightTheme: "浅色",
    darkTheme: "深色",
    notifications: "通知",
    notifPostReply: "帖子回复通知",
    notifNewFollower: "新关注者通知",
    security: "账户安全",
    currentPassword: "当前密码",
    newPassword: "新密码",
    confirmNewPassword: "确认新密码",
    changePassword: "更改密码",
    languageLabel: "语言",
    chineseOption: "中文",
    englishOption: "English",
    accountManagement: "账户管理",
    loggedInAs: "当前登录",
    switchAccountBtn: "切换账号",
    logoutBtn: "退出登录",
    // Settings extra
    managePrefs: "管理你的偏好与账户设置",
    guestModeBanner: "游客模式",
    guestModeDesc: "可以调整外观主题，账户密码修改需要登录注册账号",
    loginRequired: "登录后才能修改密码",
    themeSubLight: "默认白色背景",
    themeSubDark: "深色护眼模式",
    langSubZh: "简体中文界面",
    langSubEn: "English interface",
    notifReplies: "有人回复我的帖子",
    notifRepliesDesc: "收到新回复时通知",
    notifLikes: "有人点赞我的内容",
    notifLikesDesc: "收到点赞时通知",
    notifFollows: "有人关注了我",
    notifFollowsDesc: "被新用户关注时通知",
    notifSystem: "系统公告",
    notifSystemDesc: "平台重要通知和更新",
    enterCurrentPwd: "输入当前密码",
    enterNewPwd: "输入新密码（至少 6 位）",
    enterNewPwdConfirm: "再次输入新密码",
    pwdMinLength: "新密码至少 6 位",
    pwdMismatch: "两次密码不一致",
    pwdChanged: "密码已修改成功",
    pwdChangeFailed: "修改失败",
    networkError: "网络错误",
    loggedInAsGuest: "游客模式",
    switchAccountDesc: "登录其他账号或注册新账号",
    logoutDesc: "退出当前账号，返回登录页",
  },
  en: {
    // Auth
    login: "Log In",
    register: "Register",
    logout: "Log Out",
    username: "Username",
    password: "Password",
    confirmPassword: "Confirm Password",
    enterUsername: "Enter username",
    enterPassword: "Enter password",
    loggingIn: "Logging in...",
    registering: "Registering...",
    noAccount: "No account?",
    registerNow: "Sign Up",
    hasAccount: "Have an account?",
    loginNow: "Log In",
    // Home
    forumTitle: "AI Ethics Forum",
    forumSubtitle: "An open community for AI ethics discussion, creativity and tools",
    schoolName: "Guangdong Country Garden School",
    switchAccount: "Switch Account",
    recentLogins: "Recent",
    home: "Home",
    podcast: "Podcast",
    news: "News",
    tools: "AI Tools",
    forum: "Forum",
    creative: "Creative",
    profile: "Profile",
    settings: "Settings",
    latestPosts: "Latest Posts",
    noPostsYet: "No posts yet — be the first!",
    startDiscussion: "Start Discussion",
    browseForum: "Browse Forum",
    lastUpdated: "Updated",
    autoRefresh: "Auto-refresh",
    refresh: "Refresh",
    motto: "Motto",
    // Forum list
    forumDiscussion: "Forum",
    searchPlaceholder: "Search discussions...",
    newPost: "+ New Post",
    all: "All",
    catAiSafety: "AI Safety",
    catPrivacy: "Privacy",
    catEthics: "Ethics",
    catAcademic: "Academic",
    catSocial: "Social Impact",
    catCreative: "Creative",
    loading: "Loading...",
    noPosts: "No posts found",
    repliesCount: "replies",
    // Post detail
    backToForum: "← Back to Forum",
    guestCannotLike: "🔒 Log in to like posts",
    liked: "Liked",
    like: "Like",
    replyCount: "replies",
    replyPlaceholder: "Share your thoughts...",
    postReply: "Post Reply",
    noReplies: "No replies yet — be the first to comment!",
    guestCannotReply: "Guests cannot reply",
    loginToParticipate: "to join the discussion",
    loginLink: "Log in",
    registerLink: "register",
    postNotFound: "Post not found",
    replyFailed: "❌ Reply failed",
    // Bilingual toggle
    viewInChinese: "查看中文",
    viewInEnglish: "View in English",
    translationNotAvailable: "No English translation available",
    // New post
    newDiscussion: "Start a New Discussion",
    postTitle: "Title",
    titlePlaceholder: "Enter discussion title",
    titleEnLabel: "English Title (optional)",
    titleEnPlaceholder: "Enter title in English (optional)",
    selectCategory: "Select Category",
    contentLabel: "Content",
    contentPlaceholder: "Share your thoughts...",
    contentEnLabel: "English Content (optional)",
    contentEnPlaceholder: "Share your thoughts in English (optional)",
    publish: "Publish",
    publishing: "Publishing...",
    fillRequired: "Please fill in all required fields",
    postSuccess: "✅ Post published!",
    publishFailed: "Publish failed",
    guestCannotPost: "Guests cannot post",
    guestPostDesc: "Log in or register to start a discussion",
    // Profile
    myPosts: "My Posts",
    myBookmarks: "Bookmarks",
    myLikes: "Liked",
    myFollows: "Following",
    guestTitle: "Guest",
    guestDesc: "Guest account · Browse only, no personal page",
    loginAccount: "Log In",
    registerAccount: "Register",
    guestRegisterHint: "Register to post, reply, like, and view your stats",
    editProfile: "Edit Profile",
    saveProfile: "Save",
    cancelEdit: "Cancel",
    changeAvatar: "Change Avatar",
    bioLabel: "Bio",
    noPostsTab: "No posts published yet",
    noBookmarks: "No bookmarks yet",
    noLikes: "No liked posts yet",
    noFollows: "Not following anyone yet",
    follow: "Follow",
    unfollow: "Unfollow",
    followingState: "Following",
    followingBadge: "Following",
    followedAt: "Followed at",
    followingSectionLabel: "From people you follow",
    guestCannotFollow: "🔒 Guest mode — log in to follow users",
    usernameEmpty: "Username cannot be empty",
    usernameLimit: "Max 10 CJK chars or 20 letters",
    avatarSizeLimit: "Image must be under 2 MB. Please choose another.",
    likedPost: "Liked Posts",
    likedAt: "Liked at",
    // Settings
    appearance: "Appearance",
    themeLabel: "Theme",
    lightTheme: "Light",
    darkTheme: "Dark",
    notifications: "Notifications",
    notifPostReply: "Post reply notifications",
    notifNewFollower: "New follower notifications",
    security: "Account Security",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    changePassword: "Change Password",
    languageLabel: "Language",
    chineseOption: "中文",
    englishOption: "English",
    accountManagement: "Account Management",
    loggedInAs: "Logged in as",
    switchAccountBtn: "Switch Account",
    logoutBtn: "Log Out",
    // Settings extra
    managePrefs: "Manage your preferences and account settings",
    guestModeBanner: "Guest Mode",
    guestModeDesc: "You can adjust the theme; log in to manage account settings",
    loginRequired: "Log in to change your password",
    themeSubLight: "Default white background",
    themeSubDark: "Easy on the eyes",
    langSubZh: "Chinese interface",
    langSubEn: "English interface",
    notifReplies: "Someone replied to my post",
    notifRepliesDesc: "Notify on new reply",
    notifLikes: "Someone liked my content",
    notifLikesDesc: "Notify on new like",
    notifFollows: "Someone followed me",
    notifFollowsDesc: "Notify on new follower",
    notifSystem: "System announcements",
    notifSystemDesc: "Important platform updates",
    enterCurrentPwd: "Enter current password",
    enterNewPwd: "Enter new password (min. 6 chars)",
    enterNewPwdConfirm: "Re-enter new password",
    pwdMinLength: "Password must be at least 6 characters",
    pwdMismatch: "Passwords do not match",
    pwdChanged: "Password changed successfully",
    pwdChangeFailed: "Change failed",
    networkError: "Network error",
    loggedInAsGuest: "Guest mode",
    switchAccountDesc: "Log in with another account or register",
    logoutDesc: "Log out and return to the login page",
  },
} as const;

export type TranslationKey = keyof typeof translations.zh;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("zh");

  useEffect(() => {
    try {
      const saved = localStorage.getItem("ai_ethics_lang") as Language | null;
      if (saved === "zh" || saved === "en") setLanguageState(saved);
    } catch {}
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try { localStorage.setItem("ai_ethics_lang", lang); } catch {}
  };

  const toggleLanguage = () => setLanguage(language === "zh" ? "en" : "zh");

  const t = (key: TranslationKey): string => translations[language][key];

  const value = useMemo(() => ({ language, setLanguage, toggleLanguage, t }), [language]); // eslint-disable-line react-hooks/exhaustive-deps

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return ctx;
}
